name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "\*\! enforce v(.*) Thomas Blanchet (.*)"
        replace: "*! enforce v1.0 Thomas Blanchet 20apr2020"
